2022-10-13 15:12:55,902 |           flt.pandoc |    ERROR | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/pandoc.py", line 358, in _build_flat
    run(command, shell=True, check=True, stdout=PIPE, stderr=STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pandoc --output "Stingray-2022-10-13.docx"    -f markdown __folianttmp__/__all__.md' returned non-zero exit status 137.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/foliant/utils.py", line 158, in spinner
    yield
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/pandoc.py", line 444, in make
    result.append(self._build_flat(target))
  File "/usr/local/lib/python3.8/dist-packages/foliant/backends/pandoc.py", line 363, in _build_flat
    raise RuntimeError(f'Build failed: {exception.output.decode()}')
RuntimeError: Build failed: Killed


2022-10-13 15:12:56,749 |                  flt | CRITICAL | No result returned by backend
